### ISSUE TITLE
Image is 100 GB, can it be 10 GB?

### ISSUE THREAD

**Issue by tedb** [GoogleCloudPlatform/compute-archlinux-image-builder#16]
Hi, I noticed the pre-built image calls for a 100 GB disk image.  Is there any way this could be a 10-ish GB image like the other standard ones?  I realize I can build my own but I was thinking others might want a smaller boot disk also.

**Comment by brentsmyth** [comment]
+1  I find 20 to be a good standard (I have seen some setups get a little tight with 10gb).  100 is more of a permanent VM size.  Smaller would be better for a more "disposable" vm.

**Comment by tedb** [comment]
I feel like 20GB is fine too if it's required.  There are a few advantages to being smaller, such as launching faster and a minor reduction in PD cost.  Typical best practice has "non-system" data on a second PD anyway -- VMs should always be considered "disposable". :)

**Comment by jeremyje** [comment]
I wouldn't mind doing this. Is there any growfs tools that arch has? The annoying issue is that I couldn't find any package that would automatically grow the root file system

**Comment by dhtseany** [comment]
@jeremyje FYI 

https://wiki.archlinux.org/index.php/GNU_Parted#Resizing_Partitions

**Comment by lcastelli** [comment]
We just updated the project to a completely new implementation, which includes dynamic resizing of the root disk. Closing this issue as obsolete as it should not apply to the new version.
