### ISSUE TITLE
Set root of gce-arch-images bucket to world-readable

### ISSUE THREAD

**Issue by cceckman** [GoogleCloudPlatform/compute-archlinux-image-builder#21]
```
$:gsutil ls -l gs://gce-arch-images/*.tar.gz
AccessDeniedException: 403 Forbidden
```

It would be really nice to be able to look at the images in the bucket... without having to go to and read `README.md`.

The public can read / list individual images:

```
$:gsutil ls -l gs://gce-arch-images/arch-v20160502.tar.gz
 651521944  2016-05-02T06:55:43Z  gs://gce-arch-images/arch-v20160502.tar.gz
TOTAL: 1 objects, 651521944 bytes (621.34 MiB)
```

but not the bucket as a whole.

Can we set the R bit here- or whatever the equivalent is for GCS buckets ([READER role for allAuthenticatedUsers](https://cloud.google.com/storage/docs/cloud-console#_bucketpermission))?

**Comment by lcastelli** [comment]
We just updated the project to a completely new implementation, and images are distributed directly without having to go through Google Storage now. Closing this issue as obsolete as it should not apply to the new version.
