### ISSUE TITLE
API Updated and left this script behind

### ISSUE THREAD

**Issue by dhtseany** [GoogleCloudPlatform/compute-archlinux-image-builder#22]
Long story short, as of 12JAN2017, this script fails as follows:

```
user@gapps-project-name:~/compute-archlinux-image-builder$ ./build-arch-on-gce.sh --upload gs://cmh-custom-utilities.appspot.com/archlinux.tar.gz
Your active configuration is: [cloudshell-2036]
Creating VM to build Arch Linux
Creating Instance, archbuilder28275
ERROR: (gcloud.compute.instances.create) unrecognized arguments:
  instance-name=archbuilder28275
  instance-zone=us-central1-f
  git-source-uri=https://github.com/GoogleCloudPlatform/compute-archlinux-image-builder.git
  storage-full
You can monitor progress of the build via:
  gcloud compute instances get-serial-port-output archbuilder28275 --zone us-central1-f | grep startupscript

user@gapps-project-name:~/compute-archlinux-image-builder$
```

Nothing appears to be built and upon further reading online it seems the syntax and options used in build-arch-on-gce.sh have gone deprecated.

**Comment by dhtseany** [comment]
Also worth noting that my job these days has me using the Compute engine more and more, and I'm in a great position to help contribute to this project if you want some more help!

**Comment by lcastelli** [comment]
We just updated the project to a completely new implementation. Closing this issue as obsolete as it should not apply to the new version.
