### ISSUE TITLE
Could not change passwd via root?

### ISSUE THREAD

**Issue by KenOokamiHoro** [GoogleCloudPlatform/compute-archlinux-image-builder#23]
It complains : 
> passwd: Module is unknown
> passwd: password unchanged

**Comment by Kutabe** [comment]
Same issue.

**Comment by Kutabe** [comment]
Fixed:
/etc/pam.d/passwd     
```
-- password  required pam_cracklib.so difok=2 minlen=8 dcredit=2 ocredit=2 retry=3
-- password  required pam_unix.so sha512 shadow nullok
-- password  required pam_tally.so even_deny_root_account deny=3 lock_time=5 unlock_time=3600
++ password required pam_unix.so sha512 shadow nullok
```

**Comment by lcastelli** [comment]
We just updated the project to a completely new implementation. Closing this issue as obsolete as I believe it doesn't apply to the new version, but please follow up if that's not the case.
