### ISSUE TITLE
Latest Build should include archlinux-keyring package

### ISSUE THREAD

**Issue by gbc921** [GoogleCloudPlatform/compute-archlinux-image-builder#27]
Hi all,
I just used latest image (`v20160502`) but build can not install some packages/do a full system upgrade due to package `archlinux-keyring` being missed.

Installing vim for example gives the error of:
`:: File /var/cache/pacman/pkg/vim-runtime-8.0.1436-1-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).`

After installing keyring (`pacman -Sy archlinux-keyring`) everything works fine.

Is there a way to generate a new build and ask for a PR? (I honestly didn't look really further on how to do find that info)

**Comment by lcastelli** [comment]
We just updated the project to a completely new implementation and generated a new version of the images. Closing this issue as obsolete.
