### ISSUE TITLE
build-arch-gce locale & temporary files issues?

### ISSUE THREAD

**Issue by buck-yeh** [GoogleCloudPlatform/compute-archlinux-image-builder#29]
During run of `sudo ./build-arch-gce`, two warnings and one error are reported:

> ( 3/13) Warn about old perl modules
> perl: **warning**: Setting locale failed.
> perl: **warning**: Please check that your locale settings:
> 	LANGUAGE = (unset),
> 	LC_ALL = (unset),
> 	LANG = "en_US.UTF-8"
>     are supported and installed on your system.
> perl: warning: Falling back to the standard locale ("C").
> ( 4/13) Updating journal message catalog...
> ( 5/13) Reloading system manager configuration...
> Running in chroot, ignoring request: daemon-reload
> ( 6/13) Updating udev hardware database...
> ( 7/13) Applying kernel sysctl settings...
> ( 8/13) Creating system user accounts...
> ( 9/13) Creating temporary files...
> **error**: command failed to execute correctly
> (10/13) Reloading device manager configuration...
> Running in chroot, ignoring request.
> (11/13) Arming ConditionNeedsUpdate...
> (12/13) Updating the info directory file...
> (13/13) Rebuilding certificate stores...
> 

How can they be fixed? I am asking it here simply because I can't grok pervasively used gawk commands in short time.

**Comment by lcastelli** [comment]
The perl warnings are innocuous. Perl ends up being run by some Pacman hooks as part of the initial bootstrap before the locale is configured, and warns of the fact that the locale is indeed not configured. That's fine, it's going to get configured a few lines afterwards.

The error you get doesn't look right instead, and it's not something I can reproduce. Does it consistently happen on your runs?

**Comment by buck-yeh** [comment]
Yes, the error happens every time!

**Comment by moooofly** [comment]
The root case is related to "Running in chroot, ignoring request."
