### ISSUE TITLE
Definitley having a problem, and it could be between chair and monitor...

### ISSUE THREAD

**Issue by faddat** [GoogleCloudPlatform/compute-archlinux-image-builder#3]
So when I click on the glorious "ssh" button in the console, no dice.  It tells me that port 22 is not open.    Anyone have the miracle cure?

**Comment by jeremyje** [comment]
Arch constantly changes their setup process so this script goes out of date quickly. I made some patches and was able to create a new working image in January. I'll post the newer code later. 

You might have better luck with my fork for now.
https://github.com/jeremyje/compute-archlinux-image-builder

I'll close this once it's merged.

**Comment by jeremyje** [comment]
If you want to try out a prebuilt image use:

http://storage.googleapis.com/jeremyje/arch-stable/arch-v20150212.tar.gz

gcloud compute images create arch-v20150212 --source-uri gs://jeremyje/arch-stable/arch-v20150212.tar.gz
