### ISSUE TITLE
Use systemd-networkd instead of dhclient?

### ISSUE THREAD

**Issue by balki** [GoogleCloudPlatform/compute-archlinux-image-builder#41]
Any reason systemd-networkd is not used (which is inbuilt) instead of dhclient (which is an external package needs to be installed?). I was wondering if there is any issue with it in gcp I need to be aware of as I am planning to use for a different purpose.

**Comment by lcastelli** [comment]
Dhclient is the recommended DHCP client to use according to the GCP documentation: see https://cloud.google.com/compute/docs/import/configuring-imported-images#optimize_image. There also used to be baked assumptions in the Linux Guest Environment tools that you are indeed using dhclient, although I haven't checked whether that's still the case.
