### ISSUE TITLE
BTRFS as root?

### ISSUE THREAD

**Issue by AndreVuillemot** [GoogleCloudPlatform/compute-archlinux-image-builder#42]
Any hope for BTRFS as root instead of ext4?

**Comment by toastwaffle** [comment]
Hi Andre, apologies for the delay in responding.

I don't have a good handle on the comparative benefits of btrfs vs ext4. Are there specific benefits you're hoping to gain?

Ideally I'd like to test and benchmark such a change. We support this project on a volunteer basis only, and so we can't guarantee when we'd get around to doing that. Would you be willing to prepare a pull request for updating the build script and propose a testing strategy?

**Comment by AndreVuillemot160** [comment]
>I don't have a good handle on the comparative benefits of btrfs vs ext4. Are there specific benefits you're hoping to gain?

Two benefits is that, BTRFS has compression and it's CoW. They are pretty useful, especially since it's Arch Linux. 

> Would you be willing to prepare a pull request for updating the build script and propose a testing strategy?

Sure, I will read docs then. But can I ask what do you mean with a testing strategy?

**Comment by toastwaffle** [comment]
> what do you mean with a testing strategy?

Something that lets us verify that the performance of btrfs is at least as good as ext4 (within some margin of error)

**Comment by kaventec** [comment]
To switch the image to use `btrfs` I've made the following changes to `build-arch-gce` script. First, we format the partition to `btrfs`:           
                                                                              
    mkfs.btrfs -q -L root -- "$root_dev"                                      
                                                                              
When mounting, specify compression that is now available:                     

    mount -o defaults,compress=zstd -- "$root_dev" "$mount_dir"               

The image also needs `btrfs-progs` package:                                   

    base linux grub e2fsprogs dhclient openssh sudo google-compute-engine growpartfs btrfs-progs

In generated `fstab` also change the file system and add compression parameters:

    printf '\t%-10s' / btrfs defaults,compress=zstd                           
    
Last, but not least - change `/etc/mkinitcpio.conf` to include `btrfs` kernel module and binary:

    /^MODULES=/ { $0 = "MODULES=(virtio_pci virtio_scsi sd_mod btrfs)"; ++f1 }
    /^BINARIES=/ { $0 = "BINARIES=(fsck fsck.btrfs)"; ++f2 }

`growpartfs` seem to extend the `btrfs` partition correctly - can check in `dmesg` output. 

The above gave me a working Arch image with `btrfs`. If you don't want to setup the system in `btrfs` root, but in subvolume instead - add the subvolume creation step:

    btrfs subvolume create "$mount_dir"/root
    umount "$mount_dir"
    mount -o defaults,compress=zstd,subvol=/root -- "$root_dev" "$mount_dir"

and another change later in the script:

    printf '\t%-10s' / btrfs defaults,compress=zstd,subvol=/root
