### ISSUE TITLE
Latest image is over a year old

### ISSUE THREAD

**Issue by benhansenslc** [GoogleCloudPlatform/compute-archlinux-image-builder#43]
It is a little harder to get started with the latest image as it has become over a year old. I did the following to get started:

## 1. resolve key errors when updating the system by first updating
$ sudo pacman -S archlinux-keyring

## 2. resolve the mirror errors by updating the mirror list using a technique from https://wiki.archlinux.org/title/mirrors#Sorting_mirrors

Thanks for this project. I have found it very helpful over the years.

**Comment by toastwaffle** [comment]
Thanks for the reminder; I've deployed a new image
