### ISSUE TITLE
makepkg problem

### ISSUE THREAD

**Issue by lty1993** [GoogleCloudPlatform/compute-archlinux-image-builder#5]
The "--asroot" option is no longer supported, which causes the script stopped at installing AUR packages.

**Comment by ssasa** [comment]
Have you succeed to solve this "--asroot" not-supported-any-more issue? I have it too.

**Comment by ssasa** [comment]
BTW, I just found that this is an outdated repository and that the new one is here: 

https://github.com/jeremyje/compute-archlinux-image-builder

You should remove this repository, or at least put a README file that this is moved to a new one.

**Comment by jeremyje** [comment]
Updated
